### PR TITLE
Added a local font for offline usage

### PR DESCRIPTION
**Pull request by Alkebsi**
### The Problem 
Trying to run r3f-perf in an offline environment or an organization reserved internet connection (that blocks access to third-party URLs or CDNs) will bring errors to the console and completely hide the stats of r3f-perf, like the image below:

### The Solution 
I downloaded and optimized the Roboto font from Google Fonts. I added it to the src directory and imported it directly in TextsHighHZ.tsx.

The result, while offline:

It worked just fine in the dev environment and got built just fine. 

### Additional Size
The font initially weighted `164.69 KB`. After using [Font Squirrel](https://www.fontsquirrel.com/tools/webfont-generator), the size down to around `~26 KB`

### CODE REVIEW

**Comment by Alkebsi** [comment]
@RenaudRohlinger, I am open for editing this PR, if nessasery.

**Comment by RenaudRohlinger** [comment]
If I remember correctly there is an online tool to cherry pick the characters we want to use. For example we could re-generate the Roboto font with only 0123456789 instead, it would go down to 1kb I guess.

**Comment by Alkebsi** [comment]
> If I remember correctly there is an online tool to cherry pick the characters we want to use. For example we could re-generate the Roboto font with only 0123456789 instead, it would go down to 1kb I guess.

I will see my options and update this PR. 
Thanks for your comment ❤

**Comment by Alkebsi** [comment]
Hi @RenaudRohlinger,

I did my best to reduce it, and this was the best version at `11.66 KB`. This has the subset of the numbers only and all others, like uppercase/lowercase/special/...etc characters, will be generated from the system's default font.

I couldn't make it lighter. Have you seen one before that I can test out? I used https://transfonter.org/

**Comment by RenaudRohlinger** [comment]
Thanks!

**Pull request merged**
